# Generated by Django 5.2.6 on 2025-11-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_p_delete_registation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
            ],
        ),
    ]
