# Generated by Django 5.2.6 on 2025-12-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_m',
            name='title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='create_p',
            name='title',
            field=models.TextField(max_length=20),
        ),
    ]
