# Generated by Django 5.2.6 on 2025-12-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_create_m_title_alter_create_p_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create_m',
            new_name='Cm',
        ),
        migrations.RenameModel(
            old_name='Create_p',
            new_name='Post',
        ),
    ]
